apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app.kubernetes.io/name: demo
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: demo
  template:
    metadata:
      name: demo-pod
      labels:
        app.kubernetes.io/name: demo
    spec:
      containers:
        - name: demo-container
          image: mysql:latest
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: demo-data-mysql
      volumes:
        - name: demo-data-mysql
          persistentVolumeClaim:
            claimName: demo-pvc
