apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv
spec:
  capacity:
    storage: "500Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany # Tous les pods, peu importe l'endroit géographique, peuvent lire et écrire
    # - ReadOnlyMany # Tous les pods, peu importe l'endroit géographique, peuvent lire
    # - ReadWriteOnce # Tous les pods, d'un même endroit géographique, peuvent lire et écrire
    # - ReadWriteOncePod # Un seul pod, peu importe l'endroit géographique, peut lire et écrire
  # persistentVolumeReclaimPolicy: Retain (defaut) # On le conserve de sorte à ce qu'il ne reparte pas de zéro
  # persistentVolumeReclaimPolicy: Recycle # On le rend de nouveau disponible pour la suite des déploiements
  # persistentVolumeReclaimPolicy: Delete # On le retire de l'espace de stockage total
  storageClassName: slow
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /tmp
  #   server: 172.17.0.2
