apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  labels:
    app: nginx
    tier: frontend
spec:
  containers:
    - name: example-container
      image: nginx:latest
      resources:
        requests:
          cpu: "250m"
          memory: "64Mi"
        limits:
          cpu: "1"
          memory: "256Mi"
